/**
 * Embeds the built player SPA into the host app as a generated TypeScript
 * module. Serving from an in-memory map avoids all Metro asset / filesystem
 * friction on the phone, and gzipping keeps the whole bundle small.
 *
 * Run automatically by `pnpm --filter @familyquest/player build`.
 */
import { gzipSync } from "node:zlib";
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(here, "../dist");
const outFile = resolve(here, "../../host/assets/playerBundle.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".webmanifest": "application/manifest+json",
};

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) yield* walk(full);
    else yield full;
  }
}

const assets: { path: string; contentType: string; gzB64: string; rawBytes: number }[] = [];

for (const file of walk(distDir)) {
  const rel = "/" + relative(distDir, file).replaceAll("\\", "/");
  const ext = rel.slice(rel.lastIndexOf("."));
  const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";
  const raw = readFileSync(file);
  const gz = gzipSync(raw, { level: 9 });
  assets.push({
    path: rel,
    contentType,
    gzB64: gz.toString("base64"),
    rawBytes: raw.length,
  });
}

const totalGz = assets.reduce((sum, a) => sum + Buffer.from(a.gzB64, "base64").length, 0);

const lines: string[] = [
  "// GENERATED by apps/player/scripts/embed.ts — do not edit.",
  `// ${assets.length} assets, ${(totalGz / 1024).toFixed(1)} KB gzipped total.`,
  "",
  "export interface EmbeddedAsset {",
  "  contentType: string;",
  "  /** gzip-compressed body, base64-encoded */",
  "  gzB64: string;",
  "}",
  "",
  "export const playerAssets: Record<string, EmbeddedAsset> = {",
  ...assets.map(
    (a) =>
      `  ${JSON.stringify(a.path)}: { contentType: ${JSON.stringify(a.contentType)}, gzB64: ${JSON.stringify(a.gzB64)} },`,
  ),
  "};",
  "",
];

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"));
console.log(
  `Embedded ${assets.length} player assets → ${outFile} (${(totalGz / 1024).toFixed(1)} KB gz)`,
);
if (totalGz > 300 * 1024) {
  console.warn("⚠️  Player bundle exceeds the 300 KB gzipped budget — investigate.");
}
